# Generated by Django 6.0.4 on 2026-05-07 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('athlete_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('last_name', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=10)),
                ('event_group', models.CharField(max_length=45, null=True)),
                ('tfrrs_url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('meet_name', models.CharField(max_length=150)),
                ('meet_date', models.DateField()),
                ('event', models.CharField(max_length=45)),
                ('result_distance', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('result_time', models.CharField(max_length=20, null=True)),
                ('wind', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Track_and_Field_Performance_Management_System.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='FallTesting',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=10, null=True)),
                ('vertical', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('slj', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('stj', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sprint_50', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ohb', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('blf', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sprint_150', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Track_and_Field_Performance_Management_System.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeResult',
            fields=[
                ('practice_id', models.AutoField(primary_key=True, serialize=False)),
                ('practice_date', models.DateField(null=True)),
                ('event', models.CharField(max_length=45, null=True)),
                ('approach', models.CharField(max_length=45, null=True)),
                ('gear', models.CharField(max_length=45, null=True)),
                ('mark_meters', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('mark_raw', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('season', models.CharField(max_length=10, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWM_Track_and_Field_Performance_Management_System.athlete')),
            ],
        ),
    ]
