# Generated by Django 6.0.4 on 2026-05-08 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWM_Track_and_Field_Performance_Management_System', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UWM_Track_and_Field_Performance_Management_System.athlete'),
        ),
    ]
